#!/bin/bash

# Determine working directory
install_dir=`dirname $0`
ITFOLDER="/Users/Shared/IT"
USRSHORTNAME="$(ls -la /dev/console | awk '{print $3}')"

/usr/sbin/installer -dumplog -verbose -pkg $install_dir/"erase-install-depnotify.pkg" -target "$3"

cp $ITFOLDER/update/com.github.ygini.Hello-IT.updateme.plist /Users/$USRSHORTNAME/Library/Preferences/com.github.ygini.Hello-IT.updateme.plist
killall "Hello IT"
sleep 5
open "/Applications/Utilities/Hello IT.app"
exit 0
